[package]
name = "sanor"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["pacaunt <@pacaunt>"]
license = "MIT"
compiler = "0.13.1"
repository = "https://github.com/pacaunt/sanor"
description = "Fast, small, presentation utility"
categories = ["utility"]